### ISSUE TITLE
Make class name compatible with AnguarJS

### ISSUE THREAD

**Issue by maciej-gurban** [webpack/loader-utils#101]
Hi, I wanted to introduce CSS Module into an AngularJS project, however the way the loader parses class names won't work with angular's expressions. If file name of the imported CSS file contains a dash, the following configuration of the loader will throw cause Angular to throw the browser:
```
'css-loader?modules&localIdentName=[name]__[local]__[hash:base64:5]',
```

It will throw because dashes are not allowed in the ngClass brace expressions in Angular. Would there be a way to either provide a method to strip any non alphanumerical characters from name or wrap the name in single quotes?

**Comment by maciej-gurban** [comment]
Answering my own question, here's the loader config that satisfies my requirements:
```
const camelCase = require('lodash/camelCase');
const last = require('lodash/last');

const HASH_SIZE = 5;

const getClassName = ({ resourcePath }, localIdentName, localName, options) => {
  const fileName = last(resourcePath.split('/'));
  const className = fileName.split('.').slice(0, -1);
  const hash = Buffer.from(resourcePath).toString('base64').slice(0, HASH_SIZE);
  return `${camelCase(className)}__${localName}__${hash}`;
};

use: [
  { loader: 'css-loader',
    options: {
      modules: true,
      getLocalIdent: getClassName,
    },
  },
]

```

**Comment by evilebottnawi** [comment]
Not related to `loader-utils`, if you still have problems please create issue in `css-loader`
