### ISSUE TITLE
Max and Min of hash length

### ISSUE THREAD

**Issue by amerllica** [webpack/loader-utils#107]
Actually all of us know `css-loader` use `loader-utils`, inside of `css-loader` configuration some developers load `modules: true` and then load `localIdentName: [hash:base64:X]`.

And `X` is length variable.

I saw many of them, all of them set the `X` variable as 5 and greater than 5. why? why when I use 3, some class names made duplicate?

**Comment by milushov** [comment]
Because some css classes might have same first 3 letters of hash, like:

.foo => **ABC**XY...
.bar => **ABC**NM...

**Comment by amerllica** [comment]
Thanks @milushov , I calculate the possibility of conditions, it is so simple, `base64` can has 64 characters:
[a-z][A-z][0-9][-,_] so with 3 we can has `64 x 64 x 64` conditions, it means `262144` class names!!

So why it can not generate unique names? with 3 there are many collision class names conflicts.

**Comment by milushov** [comment]
@amerllica, because it's hash of class name, not a random string every time; you can check it by yourself -- just change value to 5 and you'll see same beginning of the hash

**Comment by amerllica** [comment]
@milushov , Thanks a lot dude, I spend all of my Friday on this problem, I wrote a sexy random function that generate all these possibilities. Just like you said `hash` is a different thing to something like my function.
