### ISSUE TITLE
`interpolateName`: Hash regex incorrectly mingles other values into the hash value

### ISSUE THREAD

**Issue by techjoshua** [webpack/loader-utils#136]
https://github.com/webpack/loader-utils/blob/489ef12a900c9f40c32eb0dceeed1eaab55fcc89/lib/interpolateName.js#L94

Regex fails for values like: `[name].[md5:hash:base64:20].[ext]`...
`getHashDigest()` is called with a `hashType = 'name].[md5'`

I suggest changing the regex to exclude closing brackets, like:
```javascript
/\[(?:([^:\]]+):)?(?:hash||contenthash)(?::([a-z]+\d*))?(?::(\d+))?\]/gi
          ^^ added
```

**Comment by webschik** [comment]
Another test case with CSS Module names:

**v1.1.x version:**
```js
/\[(?:(\w+):)?hash(?::([a-z]+\d*))?(?::(\d+))?\]/ig.exec('[name]__modalTitle___[sha1:hash:hex:4]')
...
[
0: "[sha1:hash:hex:4]"
1: "sha1"
2: "hex"
3: "4"
]

```

**v1.2.x version:**
```js
/\[(?:([^:]+):)?(?:hash||contenthash)(?::([a-z]+\d*))?(?::(\d+))?\]/gi.exec('[name]__modalTitle___[sha1:hash:hex:4]')
...
[
0: "[name]__modalTitle___[sha1:hash:hex:4]"
1: "name]__modalTitle___[sha1"
2: "hex"
3: "4"
]
```

**Comment by evilebottnawi** [comment]
Fixed in https://github.com/webpack/loader-utils/releases/tag/v1.2.2
