### ISSUE TITLE
Remove emoji interpolation

### ISSUE THREAD

**Issue by devoto13** [webpack/loader-utils#142]
I would like to deprecate and drop [`[emoji]` interpolation](https://github.com/webpack/loader-utils#interpolatename) together with `emojis-list` library from the dependencies. I understand emojis are so fun and all that, but forcing whole ecosystem to pull couple of KB of emojis to power the feature, which only a handful of people uses does not feel very professional.

It should be done as a separate library if done at all.

Any thoughts on this?

**Comment by evilebottnawi** [comment]
@devoto13 couple of KB? You don't need include loader-utils in your production bundle, also it is break a lot of app, so it can be done

**Comment by devoto13** [comment]
No, sure it is not in bundle, in `node_modules`. But I don't see why `npm install` has to install half of the internet on my computer.

Well, that's why I say *deprecate and drop*, so it will take at least two major versions and people will have time to migrate.

I don't see why ability to interpolate emojis should be part of the core functionality of Webpack. Extension, file name, content hash, emojis... Don't you feel that something is odd with the list of core interpolations?

**Comment by evilebottnawi** [comment]
@devoto13 it is often used for `interpolation` css classes

**Comment by devoto13** [comment]
I see, just found information on this [interesting practice](https://twitter.com/addyosmani/status/702976873467408386). So then can it be a dependency of `css-loader`?

I don't have any CSS in the project and `ts-loader` doesn't seem to need emojis.

**Comment by evilebottnawi** [comment]
@devoto13 what is problem with emoji? Don't use their

**Comment by devoto13** [comment]
The problem is not emojis per se. The problem is bloated `node_modules` most of which is not used by the project. The goal is to remove non-essential dependency, so projects, which don't use it don't have to download it.

**Comment by evilebottnawi** [comment]
@devoto13 use pnp feature to avoid unnecessary install, `emoji` take up very little space compared to any other library

**Comment by devoto13** [comment]
I'm not sure what is *pnp* feature you refer to.

There are hundreds of maintainers, which said the same thing about another *tiny* library. And all these small libraries depending on other small libraries, they add up resulting in bloated `node_modules` we have now. Isn't it better to keep the house clean at the first place?

**Comment by evilebottnawi** [comment]
@devoto13 not in this cases, as i said above some developers use emoji for interpolation in css and not all, so it should be part of this lib and can't be removed in near future

**Comment by devoto13** [comment]
The key is *some* here. AFAIK majority of Angular community don't do this, create-react-app does not seem to do it either. Aren't these two the biggest consumers of Webpack? This leaves us with the minority of developers, who do their Webpack build manually and only some unknown part of them using emojis for CSS. I do struggle to find much information about this on Google either, which leads me to the conclusion that this is rather not commonly used feature.

Anyway if you think that it doesn't matter feel free to close the issue. I have already made all my arguments.

**Comment by evilebottnawi** [comment]
@devoto13 we move loader api in webpack for webpack@5 and emoji will be removed, so don't worry we solve this in near future
