### ISSUE TITLE
stringify object to pass to loader

### ISSUE THREAD

**Issue by dtothefp** [webpack/loader-utils#15]
I placed this issue https://github.com/jtangelder/sass-loader/issues/155 on `sass-loader` but maybe it is more appropriate there. I'm trying to figure out how to `stringify` an object to be parsed by `loader-utils`. I tried using `json5` directly with no luck, and tried `encodeURIComponent` on the stringified object but when it is parsed it is a string not an object. Is there some way to accomplish this?

``` js
let functions = {
  'image-url($filename)': function(filename) {
    var imageUrl = process.env.NODE_ENV === 'development' ?
      '' :
      '';//enter CDN path here
    var fileName = filename.getValue();

    var imagePath = 'url("' + imageUrl + '/' + fileName + '")';
    /*eslint-disable */
    return new sass.types.String(imagePath);
    /*eslint-enable */
  }
}

`sass-loader?functions=${somehowStringify(functions))}`
```
##### Update: got passing object as query param to work, but still found no way to do this programmatically by stringifying a series of objects

![screen shot 2015-08-31 at 9 02 29 am](https://cloud.githubusercontent.com/assets/4656726/9579594/d725d06c-4fc1-11e5-820a-d028b74627db.png)

**Comment by sokra** [comment]
You cannot stringify a function. You cannot pass a function as query param to loader (no way).

Anyway to correct way (doesn't work in your case, because of functions) would be:

``` js
"sass-loader?" + JSON.stringify({functions: function})
```

---

Complex loader config need to be passed over webpack configuration. (cc @jhnns)

**Comment by jhnns** [comment]
@sokra is right. That's why the sass-loader prefers the config to be set on the webpack config object:

```javascript
// webpack.config.js

module.exports = {
    sassLoader: {
        functions: {
            ...
        }
    }
};
```

**Comment by dtothefp** [comment]
@jhnns yeh this is an old issue. At the time of writing it you hadn't added the config option yet and could only pass options as query params

**Comment by jhnns** [comment]
Oh ok ^^

**Comment by jhnns** [comment]
Starting with webpack 2, you can pass options to loaders without stringifying them.
