### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by vankop** [webpack/loader-utils#151]
**Feature request**

Regarding to https://github.com/webpack/schema-utils/issues/49 it will be great to support TypeScript definitions here as well. It will be useful for `ts-loader` and `awesome-typescript-loader`, how it handled currently:
https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts#L10
https://github.com/TypeStrong/ts-loader/blob/master/src/typings/loaderUtils/loaderUtils.d.ts

**Comment by evilebottnawi** [comment]
We want to move this stuff inside webpack, so i think no need do this right now here
