### ISSUE TITLE
interpolateName in a plugin

### ISSUE THREAD

**Issue by eugene-manuilov** [webpack/loader-utils#153]
Hello,

could you please advice me how to properly use `interpolateName` in a plugin? I am working on a plugin that should emit supplementary files based on the source code of a chunk and i can't figure out how to properly compose a name for my files using placeholders like `[name]`, `[hash]`, etc. What do i need to pass into `loaderContext` and `options` params and where can i take it?

Thanks in advance!

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/postProcessPattern.js#L120
