### ISSUE TITLE
Why query strings are removed when interpolating the name?

### ISSUE THREAD

**Issue by Powell-v2** [webpack/loader-utils#161]
Hi,

I'd like to know why `interpolateName` helper removes query strings from file paths? Is this intentional?

Thanks in advance for the explanation.

**Comment by evilebottnawi** [comment]
Answer was in file-loader repo, it is not removed by `interpolateName` (https://github.com/webpack/loader-utils/blob/master/test/interpolateName.test.js#L77), it is internal behavior in webpack
