### ISSUE TITLE
Please release v1.4.1 to fix a vulnerability

### ISSUE THREAD

**Issue by t3-aoki** [webpack/loader-utils#169]
There are a lot of loaders which still use `loader-utils v1.x`.

Please release https://github.com/webpack/loader-utils/commit/c78786d5b540dea5e50d741557c72f2523976ef3 as v1.4.1 to fix a vulnerability.

**Comment by evilebottnawi** [comment]
Sorry, no, you need to update `loader-utils`, v1 is deprecated and even create a problem, please open an issues in repos which still uses old version
