### ISSUE TITLE
[feature-request] Parsing a number in query

### ISSUE THREAD

**Issue by cdoublev** [webpack/loader-utils#173]
Hello,

I would like to sugget parsing a `Number` in the value of a query parameter used to set options of a loader. 

```diff
 if (specialValues.hasOwnProperty(value)) {
     value = specialValues[value];
- }
+ } else if (/^\d$/.test(value) {
+     value = Number(value)
+ }
```

https://github.com/webpack/loader-utils/blob/d9f4e23cf411d8556f8bac2d3bf05a6e0103b568/lib/parseQuery.js#L39

Is there a reason to parse a `Boolean` but not a `Number`? Performances?

Eg. `css-loader?importLoaders=true` works but not `css-loader?importLoaders=1`.

Note that having `css-loader?importLoaders=true` not throwing an error is also confusing, since the [`css-loader` doc](https://github.com/webpack-contrib/css-loader#importloaders) states that only a `Number` is expected. Please feel free to ask me to create a new issue in the related repository.

**Comment by evilebottnawi** [comment]
Sorry, this utils only for compatibility with webpack@4, for webpack@5 it was deprecated, because `getOptions` built-in webpack@5, so we don't accept features

**Comment by evilebottnawi** [comment]
Anyway this we should solve on css-loader side

**Comment by evilebottnawi** [comment]
Using `parseInt`, feel free to open an issue

**Comment by cdoublev** [comment]
Don't you think it's related to `schema-utils`?

https://github.com/webpack-contrib/css-loader/blob/835335361cd012f7db114d0c648e4f364050181c/src/index.js#L34

**Comment by evilebottnawi** [comment]
@cdoublev we should allow `importLoaders` to be `string` and use `parseInt` to get value
