### ISSUE TITLE
RFC: add uglify token to interpolateName

### ISSUE THREAD

**Issue by TroyTae** [webpack/loader-utils#174]
### Summary

moved from https://github.com/webpack-contrib/file-loader/issues/380
How about add uglify token to `interpolateName`?
If we use ugly name in production, we can get lighter bundle file.

### Syntax

- `[ugly-name:<uglyType>]`
  - uglyType => `word`, `file`, `css`, etc... (default: word)

Reference: https://github.com/TroyTae/uglify-set

**Comment by evilebottnawi** [comment]
Send a PR
