### ISSUE TITLE
Absolute paths in Windows are treated as relative paths.

### ISSUE THREAD

**Issue by Auxx** [webpack/loader-utils#19]
urlToRequest() only checks slash at the beginning of a string to determine if path is absolute or relative. DOS styles paths (c:\path\somewhere) and UNC paths (\\device\path\somewhere) are ignored and treated as relative ones.

**Comment by Auxx** [comment]
A proposed fix for this behaviour is commited as a [pull request](https://github.com/webpack/loader-utils/pull/20).

**Comment by sokra** [comment]
done
