### ISSUE TITLE
v2.0.2 release has breaking changes

### ISSUE THREAD

**Issue by alexpovh** [webpack/loader-utils#199]
[edited]
v2.0.2 fixes the base64 logic to output a correct base64 hash, but the correct base64 hash contains invalid css characters `+/=` and this can break unsanitized calls to `document.querySelector` function.

The dependency is webpack@4 -> css-loader@5 -> loader-utils@2

**Comment by alexander-akait** [comment]
Because we have wrong `base64` output, also `loader-utils@2` is deprecated, please show your problem

**Comment by alexander-akait** [comment]
Changing hash is not breaking change, it is fix

**Comment by alexpovh** [comment]
I agree it's a fix, but one of our projects had an issue where developers depend on the css-loader standard base64 hash function and used the generated css class names directly to call `document.querySelector` function but after v2.0.2 this stopped working because `document.querySelector` doesn't like some of the proper base64 characters. I'm not sure how widespread this issue is, just wanted to share.

**Comment by alexander-akait** [comment]
Please provide example

**Comment by alexpovh** [comment]
Here is an example of code that breaks with 2.0.2 fix:

app.jsx
```
import React, { useEffect } from 'react';
import styles from './Styles.module.css';

export default () => {
  useEffect(() => {
    const anchors = document.querySelectorAll(`.${styles.colorStyle} a`)
    // do something with anchors
  })

  return (
    <div className={styles.colorStyle}>
      <a href="https://some.where">link</a>
    </div>
  )
}
```

Styles.module.scss
```
.colorStyle {
  color: green
}
```

partial webpack config:
```
{
    module: {
      rules: [
        {
          oneOf: [
            {
              test: /\.module\.(scss|sass)$/,
              use: [
                {
                  loader: MiniCssExtractPlugin.loader,
                },
                {
                  loader: require.resolve('css-loader'),
                  options: {
                    importLoaders: 1,
                    modules: true,
                  },
                },
                {
                  loader: require.resolve('sass-loader'),
                  options: {
                    implementation: sass,
                  },
                },
              ].filter(Boolean),
            },
          ]
        }
      ]
    }
}
```

The above throws the following error when loaded in the browser:
```
Uncaught DOMException: Document.querySelectorAll: '.X-4WM3KfVRgjSvIHYIvOcw== a' is not a valid selector
```

**Comment by alexander-akait** [comment]
It was answered a lot of time, you need escape selector before passing it in JS, there are a lot of other cases when you have it

**Comment by alexander-akait** [comment]
Using `CSS.escape`, event more, you have potential XSS

**Comment by alexpovh** [comment]
oh, I understand that it needs to be escaped and that's the fix we already applied, if you don't think there is a need to worry about the cases when it's not properly escaped please feel free to close this issue.

**Comment by alexander-akait** [comment]
Maybe we should docs it in `css-loader`, feel free to send a PR to `css-loader` docs, let's close here
