### ISSUE TITLE
loaderUtils.getOptions is not a function

### ISSUE THREAD

**Issue by jiakaiqiang** [webpack/loader-utils#201]
I try to use the latest version of loader uitls to write a loader, but GETOPTION () is not a function. In addition, getloaderconfig () also shows that it is not a function. Try switching to version 1.2.3 to get it. How to solve the problem of the latest version? You can use this project **https://github.com/zyqq/make-loade**r Modify the version of loader uitls to the latest version，thank you

**Comment by alexander-akait** [comment]
It is breaking change, you need webpack v5 to use `this.getOptions`, `getOptions` was removed, if you need webpack v4 support please use v2
