### ISSUE TITLE
Prettier show all files with error because of default

### ISSUE THREAD

**Issue by peter-spireng** [webpack/loader-utils#203]
Clone repository and run "yarn test" - prettier will show error in files because of end of lines. There is no prettier config, so it expect "lf" on end of line (from version 2.0.0 - https://prettier.io/docs/en/options.html#end-of-line) but currenty there is "crlf" in files.
I can prepare PR but what is right option: add .prettierrc with "crlf" end of line configuration value or change end of line in source files to "lf"?

**Comment by alexander-akait** [comment]
We use `lf`, I think something wrong with `.gitattributes`

**Comment by peter-spireng** [comment]
I dont see any .gitattributes file in loader-utils repo ... probably we should add  it

**Comment by alexander-akait** [comment]
Yes, we should add, feel free to send a PR
