### ISSUE TITLE
is 2.0.4 in the NPM registry?

### ISSUE THREAD

**Issue by JosephNewman26** [webpack/loader-utils#232]
npx: installed 6 in 9.643s
npm ERR! code ETARGET
npm ERR! notarget No matching version found for loader-utils@2.0.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

I keep getting no target matching the 2.0.4 version of loader utils. Is it in the npm registry yet?

Thank you.

**Comment by alexander-akait** [comment]
Yes, please look at https://www.npmjs.com/package/loader-utils?activeTab=versions

**Comment by JosephNewman26** [comment]
When I click on 2.0.4 i get an error as seen in the image below.
![image](https://user-images.githubusercontent.com/113563372/204399516-24a16f75-8e3c-4200-9645-2acc00e4a53f.png)

Can you please be more specific.

**Comment by alexander-akait** [comment]
Sounds like bug on `npm` side, we can't fix it here

**Comment by JosephNewman26** [comment]
Okay, got it. Thank you.
