### ISSUE TITLE
Specify what to hash

### ISSUE THREAD

**Issue by opatut** [webpack/loader-utils#28]
(Originally posted at webpack/file-loader#60)

I'd like to be able to specify what to mangle through the hash function in order to get the `[hash]`. In my specific case, I want to hash `[path][name]`. I would like to have an additional parameter in the `[hash]` brackets that specifies a pattern (to be interpolated with `interpolateName`) for what to hash.

Rationale: we're building different versions that are served based on the request origin, but using the same js bundle (and server side code!), but with different file contents (e.g. different images at `logo.png`). If we were to hash the content, the different file had a different hash, and we could not map it from the one the js bundle requested. We don't want to use `[path]` in production either because it gives away our file structure. Hence we'd like to hash the path.

I also want to to be able to add two different hashes, one using the `path`, one using file content, to the generated name. We need this for the version suffix to trick the browser cache, i.e. generate `[hash:[path]]/[name]-[hash:6].[ext]`.

**Comment by sokra** [comment]
see comment in PR
