### ISSUE TITLE
Update dependencies?

### ISSUE THREAD

**Issue by kmck** [webpack/loader-utils#31]
Hi! I noticed that installing `loader-utils` brings a _lot_ of cruft with it, most of it from the `json5` dependency. That issue was identified and [fixed](https://github.com/aseemk/json5/pull/109), but `loader-utils` is depending on `^0.4.0`. I did a quick check, and it seems like updating `json5` to the latest version (and `big.js` for that matter) doesn't seem to break anything and the tests still pass.

Any chance you could update these dependencies and publish an updated version of this on npm? Happy to submit a pull request if that makes it easier.

**Comment by sokra** [comment]
done

**Comment by kmck** [comment]
thanks!
