### ISSUE TITLE
Can no longer handle % symbol in parseQuery

### ISSUE THREAD

**Issue by paulbarr** [webpack/loader-utils#35]
I am using the loader-util to optimise less files
I have seen the following defect appear between versions 0.2.13 and 0.2.14
"malformed URL"
This is becasue in this commit "ee056c9f8fcfef913f64b6b879a59b2747d412fb" (from 3 days ago) you have introduced decodeURIComponent
So the line of code below that used to work, now gives the malformed URL issue
`css${mapQ}!autoprefixer${mapQ ? mapQ + '&' : '?'}{ "browsers": ["last 2 versions","> 5%"] }!less${mapQ}`

**Comment by brianac** [comment]
I am experiencing the same issue with scss and autoprefixer. We're using `css-loader` but it's dependant on this module.
```
        test: /\.scss$/,
        loader: [
          'css',
          '!autoprefixer?browsers=last 2 versions, > 1%, Firefox ESR, ie >= 9',
          '!sass?includePaths[]=src/styles/components/'
        ].join('')
```
Getting `URIError: URI malformed` errors. I don't think using `decodeURIComponent` allows for every use case.

**Comment by szydan** [comment]
This seems to be breaking kibana builds as well 
reported here 
https://github.com/elastic/kibana/issues/6858 
https://github.com/elastic/kibana/issues/6885

**Comment by jhnns** [comment]
Use `encodeURIComponent` or even better `JSON.stringify()` if you're using query strings:

```js
    test: /\.scss$/,
        loader: [
          'css-loader',
          'autoprefixer-loader?' + JSON.stringify(autoprefixerOptions),
          'sass-loader?' + JSON.stringify(sassOptions)
        ].join('!')
```

Starting with webpack 2, you can specify an `options` object which is not stringified anymore.
