### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...).filter is not a function

### ISSUE THREAD

**Issue by p2227** [webpack/loader-utils#36]
step1 

```
npm install -g yo generator-react-webpack-redux
```

step2 

```
# Create a new directory, and `cd` into it:
mkdir my-new-project && cd my-new-project

# Run the generator
yo react-webpack-redux
```

now if you `npm start` it works.
step3

```
npm i react-router react-router-proxy-loader -S
```

step4
modify `index.js` and add

```
import 'react-router';
import 'react-router-proxy-loader';
```

**then it throw error above**

the error code is  https://github.com/webpack/loader-utils/blob/ee056c9f8fcfef913f64b6b879a59b2747d412fb/index.js#L5

```
var emojiList = require("emojis-list").filter(function(emoji) {
    return emojiRegex.test(emoji)
});
```

step5
modify `index.js`:

```
import 'react-router';
// import 'react-router-proxy-loader';
```

there is no error again

I think there are some conflicts between `webpack` `loader-utils` `emojis-list` and `react-router-proxy-loader`

**Comment by p2227** [comment]
**finally I solve it by adding `json-loader`**


the conflict is : `emojis-list` exports a json file. there is no problem while it is in node/commonjs environment.
but in webpack , the `require` function is rewrite to `__webpack_require__` . it can't load json file without json-loader

**Comment by jhnns** [comment]
The loader-utils are designed to be used in a node.js environment. I cannot think of a situation where you want to include your *loader* in your bundle :)
