### ISSUE TITLE
Check for loaderContext in 'getRemainingRequest' and 'getCurrentRequest'

### ISSUE THREAD

**Issue by necolas** [webpack/loader-utils#4]
I have a loader that contains the call `.getRemainingRequest(this)`. In my tests, I have `loader.call({}, 'some string')` which throws the following error due to the lack of `loaderContext`:

```
TypeError: Cannot call method 'slice' of undefined
      at Object.exports.getRemainingRequest (/project/node_modules/loader-utils/index.js:46:38)
      ...
```

Like `parseQuery`, perhaps these methods should not assume a context will always be provided?

**Comment by jhnns** [comment]
I think, this is not relevant anymore because `getRemainingRequest` is not accessing the `context` anymore.
