### ISSUE TITLE
Custom interpolateName tokens

### ISSUE THREAD

**Issue by soluml** [webpack/loader-utils#43]
**Feature Request:**
Would love the ability to specify my own tokens that tie into a callback of sorts for other webpack loaders.

This is in reference to a Github issue for [css-loader](https://github.com/webpack/css-loader/issues/101).

**Comment by soluml** [comment]
Pull request for this feature -> https://github.com/webpack/loader-utils/pull/45

**Comment by evilebottnawi** [comment]
Fixed in `css-loader`. Feel free to feedback
