### ISSUE TITLE
isUrlRequest return true when test 'about:blank'

### ISSUE THREAD

**Issue by luqingxuan** [webpack/loader-utils#46]
in my css file, there is a css rule
body {
background-image: url('about:blank');
}
css-loader call loadUtils.isUrlRequest method, 
and this method return true, so css-loader try to read this file ,
but u konw this file does not exits, so if there is a bug exits?

**Comment by michael-ciniawsky** [comment]
@luqingxuan Disable 'css-loader` 's url() parsing with

**webpack.config.js (webpack v2)**
```js
{
  loader: 'css-loader',
  options: { url: false }
}
```

or 

```js
const css = require(css-loader?-url./file.css)
```

**Comment by jhnns** [comment]
What's the use-case of specifying `about:blank`?

**Comment by luqingxuan** [comment]
@jhnns 
import a jquery plugin, it has csss rule like this.
body {
background-image: url('about:blank');
}
