### ISSUE TITLE
`parseQuery` array support

### ISSUE THREAD

**Issue by rhys-vdw** [webpack/loader-utils#47]
Is there a standard way to represent arrays in a loader query?

```js
utils.parseQuery('?a=1&a=2&a=3')
// -> { a: "3" }
```

**Comment by marcfallows** [comment]
If you postfix the key with `[]` then you get array behaviour:
```
utils.parseQuery('?a[]=1&a[]=2&a[]=3')
// -> { a: ["1", "2", "3"] }

**Comment by rhys-vdw** [comment]
Ah, it's even documented in the README. Thanks for the response.
