### ISSUE TITLE
getOptions: query VS. options

### ISSUE THREAD

**Issue by maxkoryukov** [webpack/loader-utils#69]
Looks, like `getOptions` works only with one **config-source**. Let me explain :wink:

My `webpack.config.js` looks like this (not exactly the same, but similar and it's enough):

```js
var appConfig = {
	"aaaaaaaaaaaa": 111
}
// ....
var webpackConfig = {
// ....
			{
				test: /[\/\\]package\.json$/,
				loader: "json-string-loader?json1=" + JSON.stringify(appConfig),
				options: {
					json2: { "sssssssssss" : new Date() }
				},
			}

// ....
}

module.exports = webpackConfig
```

In my `*-loader` am calling `const opt = util.getOptions(this)`

### Expected

I am waiting for:

```js
opt = {
    json2: { "sssssssssss": "2017-02-21T23:41:56.442Z" },    // from options
    json1: { "aaaaaaaaaaaa": 111 },                          // from query
}
```

### Current result

I have just the `options` part:

```js
opt = { json2: { "sssssssssss": "2017-02-21T23:41:56.442Z" } }
```

----

I could get the content of the query, but I **must** delete the `options` sections of the loader from `webpack.config.js`

Such behavior is implemented here: https://github.com/webpack-contrib/file-loader/blob/v0.10.0/index.js#L21

**Comment by jhnns** [comment]
> Looks, like getOptions works only with one config-source

Yes. That's a known limitation and it was introduced by overloading `this.query`. `this.query` is the `options` object from the `webpack.config.js` or – if no options object was given – the actual query. I think, @sokra decided to overload it because it makes every loader compatible with webpack 2 by default, but it also introduced the problem of multiple loader invocations sharing the same options object (see #56).

Just merging the objects is kind of risky, because merging objects is a non-trivial task. For example: Should arrays be merged?

The new [rules configuration](https://webpack.js.org/configuration/module/#module-rules), however, allows [to map query strings to specific options](https://webpack.js.org/guides/migrating/#advanced-loader-matching).

With a configuration like this:

```javascript
            {
                resource: /a\.js$/,
                resourceQuery: /^\?1$/,
                use: [{
                    loader: "my-loader",
                    options: {
                        1: true
                    }
                }]
            },
            {
                resource: /a\.js$/,
                resourceQuery: /^\?2$/,
                use: [{
                    loader: "my-loader",
                    options: {
                        2: true
                    }
                }]
            }
```

you can invoke `my-loader` with different options depending on the query string

```javascript
import a1 from "./a.js?1";
import a2 from "./a.js?2";
```

**Comment by sokra** [comment]
`options` is just an alias for `query`. So passing query and options is wrong (there should probably an error in this case, but this is a webpack/webpack issue).

**Comment by bebraw** [comment]
Yeah, disallowing both `options` and `query` at one (or at least warning) would be nice as otherwise it hides the issue.

**Comment by jhnns** [comment]
> options is just an alias for query. So passing query and options is wrong (there should probably an error in this case, but this is a webpack/webpack issue).

You mean, the `query` property is an alias. But the actual resource query is not an alias. The `options` object from the `webpack.config.js` shadows the actual resource query. With the previous webpack 1 behavior, it was possible to merge the resource query and the options from the `webpack.config,js`.

**Comment by sokra** [comment]
`loader: "json-string-loader?json1=abc"` sets the loader query not the resource query. You can't set the resource query from configuration.

`loader: "json-string-loader?json1=abc"` is equal to `loader: "json-string-loader", query: "json1=abc"`

**Comment by jhnns** [comment]
Yes, thanks for clarifying that.

But my previous comment still applies 😁

**Comment by maxkoryukov** [comment]
does it make sense to add an explicit warning about such behavior to the documentation? To this module or into the [webpack documentation](https://webpack.js.org/)?

About errors, mentioned by @sokra ... :

> passing query and options is wrong (there should probably an error in this case, but this is a webpack/webpack issue)

... it would be very useful, and clear. Throwing such errors will prevent creation tickets like this one:)

**Comment by maxkoryukov** [comment]
@jhnns thank you for an answer!

**Comment by jhnns** [comment]
> does it make sense to add an explicit warning about such behavior to the documentation?

I think, it makes more sense to catch this mistake with the config validation. If we add all possible invalid configurations to the docs, they would be awful long 😁

**Comment by bebraw** [comment]
Yeah, push everything possible to the tool. It's hard to remember exceptions. Better let the machine do it.
