### ISSUE TITLE
There is no chunk infos we can use in loaders.

### ISSUE THREAD

**Issue by Emiya0306** [webpack/loader-utils#72]
I don't find any string template which let me get chunk name in loaders. In [TemplatedPathPlugin](https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js#L70), I can get the chunkName by "[name]", and file name by "[file]".

I expect let the templates the same as webpack's template. It will be more cool and easy to use.
Just like the config below.
```javascript
{
  test: /\.png$|\.jpg$|\.gif$/,
  use: [
    {
      loader: 'url-loader',
      options: {
        name: '[name]/images/[file]-[hash].[ext]',
        limit: '5000'
      }
    }
  ]
}
```

**Comment by sokra** [comment]
No, and this is not possible. Chunks are created after loaders/modules.
