### ISSUE TITLE
renaming "parseQuery" to "getOptions" without a major version change causes some of its dependent packages to break

### ISSUE THREAD

**Issue by settinghead** [webpack/loader-utils#73]
Since the renaming is a breaking change, it has broken some of its dependent packages (For example: https://github.com/sveltejs/svelte-loader/blob/master/index.js#L2)

I think a "gentler" approach would be to either maintain backward compatibility, or update the major version number. Just FYI. :)

**Comment by jhnns** [comment]
It was [a breaking change](https://github.com/webpack/loader-utils/releases/tag/v1.0.0).
