### ISSUE TITLE
Show loader name together with deprecation warning

### ISSUE THREAD

**Issue by AlexKvazos** [webpack/loader-utils#75]
Currently deprecation warnings are logged without the name of the loader that caused the issue.

The only way of debugging this is to try each loader one by one to see which one is shooting that warning.

**Comment by jhnns** [comment]
Put [`process.traceDeprecation = true`](https://nodejs.org/api/util.html#util_util_deprecate_function_string) inside your `webpack.config.js` and node will output a stack trace. Alternatively, you can also start your process with `node --trace-deprecation node_modules/.bin/webpack`

This is node's default way of handling deprecations. The [usability is not good](https://github.com/webpack/loader-utils/issues/56#issuecomment-282649498), but [we've brought that already up](https://github.com/nodejs/node/issues/11703).

**Comment by ryanve** [comment]
Is `process` meant to be key in the webpack config object or the node built-in `process`?

**Comment by scholtzm** [comment]
@ryanve I couldn't get the `process` flag to work, had to use the CLI switch at the end.

**Comment by ryanve** [comment]
Thanks @scholtzm
