### ISSUE TITLE
[request] Export parseQuery

### ISSUE THREAD

**Issue by anseki** [webpack/loader-utils#76]
Hi, thank you for the useful tool.

So, I understand that the `getOptions` is provided instead of the `getLoaderConfig` and `parseQuery`, in new version.
But I hope that the `parseQuery` is exported by new version also because that is useful for parsing other query strings e.g. `context.resourceQuery`.

loader-utils still has the `parseQuery`, and we can import it by

```js
require(path.resolve(path.dirname(require.resolve('loader-utils')), 'parseQuery.js'))
```

Of course I know this is not good way.
I hope that the loader-utils exports the `parseQuery` and supports it.

**Comment by jhnns** [comment]
Agreed. I haven't thought about that. Could you make a pull-request and add a small note to the README?

**Comment by anseki** [comment]
Thank you @jhnns,
Ok, I try to send PR later.
But my English is poor, and please help me if something wrong.

**Comment by austinhinderer** [comment]
Could you bump the patch version so NPM will pickup this update?
