### ISSUE TITLE
Fat arrow (=>) style functions break IE11

### ISSUE THREAD

**Issue by adamholdenyall** [webpack/loader-utils#92]
I recently upgraded a site from Angular2 to Angular4 which cascaded eventually to an upgrade of awesome-typescript-loader which pulled in an up-to-date loader-utils.

However, I found that I got a runtime error in loader-utils when running my site in IE11. Diving deeper, it looks like files like parseQuery in this library are full of fat arrow functions, which break IE11.

Is this library intentionally targeting es6-only? Can these functions be rewritten with the function(){} traditional syntax to prevent this?

**Comment by northkode** [comment]
This build breaks more then ie 11 it breaks webpack packing as it doesn't know what let or => arrow are..

**Comment by smattt** [comment]
We're also impacted by this change as we need to support IE11 for a few customers with strict IT requirements. Bumping for attention. Thanks

**Comment by 3stacks** [comment]
My builds are fine in production mode (the utils don't appear to be in the bundle), but in dev mode they're there, which makes it very difficult to debug issues in IE11.

**Comment by veebz** [comment]
This is most likely not an issue with loader-utils.  Webpack loader source code is not included in the chunk that is emitted.  Only the results of the evaluated loader function are included.  You can test this yourself by adding a loader such as file-loader to a bare bones project and watch how the output changes.

This is probably an issue with the configuration of a specific loader.  When using webpack loaders, one common cause of accidental future syntax in your final output is a babel plugin nested in a webpack loader.  It is common for such loaders to emit JavaScript in non-transpiled future syntax.  This way, the resulting output can be better optimized later on or left unchanged for targeting modern browsers.

If a consumer of that plugin wants to transpile that code (to es2015 for example), one common convention is to pass babel-loader as an additional loader for the given rule in their webpack config.  Also, include a .babelrc file or pass an options object to the babel-loader.  For example:
```
{
  test: /\./,
  use: [
    {
      loader: "babel-loader",
      options: {
        presets: ["babel-preset-es2015"],
      },
    },
    { loader: "loader-which-emits-es6-code" },
  ],
}
```

**Comment by jscinoz** [comment]
This issue can occur with the [common pattern](https://webpack.js.org/guides/shimming/) of using `imports-loader` to polyfill globals - `imports-loader` pulls in `loader-utils` which contains an arrow function in `getCurrentRequest`, causing a syntax error in IE11, as third-party code is generally not transpiled in most projects.

**Comment by evilebottnawi** [comment]
You don't need build `loader-utils` for browser, but if you really want this, please use `babel` to avoid problem with compatobility
